"""FIX: removed defaul value from district and made supplier defaul user_type

Revision ID: 37cfbcc0ebd3
Revises: 463625dca6be
Create Date: 2025-10-27 11:01:10.524256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cfbcc0ebd3'
down_revision: Union[str, None] = '463625dca6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
